import type { NextPage } from "next";
import Head from "next/head";
import Scroll from "../components/Scroll";

const Home: NextPage = () => {
  return(
    <div className="w-full h-full">
      <Head>
        <title>Swupel_PMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pageLogo.ico" />
      </Head>
      <Scroll/>
    </div>
  )
}

export default Home;